on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  jobs:
  step:
  name: Deploy to Azure Static Web Apps
   uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
